name: Update Screenshots on Code Change

on:
  push:
    branches: [main, master]

env:
  UPDATE_SCREENSHOTS: "true"

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests in screenshot update mode
        run: pytest --browser chromium

      - name: Prepare screens branch
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Создание чистой ветки
          git checkout --orphan screens
          git reset --hard

          # Копирование скриншотов
          find . -type d -path "*/screenshots/reference" | while read dir; do
            mkdir -p "screens-branch/${dir}"
            cp -r "${dir}"/* "screens-branch/${dir}/"
          done

          # Первый коммит
          echo "# Reference Screenshots" > README.md
          git add .
          git commit -m "Update reference screenshots [skip ci]"

      - name: Push to screens branch
        run: git push origin screens --force
