name: Update Screenshots on Code Change

on:
  push:
    branches: [main, master]

env:
  UPDATE_SCREENSHOTS: "true"

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests in screenshot update mode
        run: pytest --browser chromium --headless -k "not compare" # Исключаем тесты сравнения

      - name: Prepare screens branch
        run: |
          git checkout --orphan screens
          git rm -rf .
          git clean -fxd
          echo "# Reference Screenshots" > README.md
          git add README.md
          git commit -m "Initialize screens branch"

      - name: Copy reference screenshots
        run: |
          find . -name "reference" -type d | while read dir; do
            mkdir -p "screens-branch/${dir}"
            cp -r "${dir}"/* "screens-branch/${dir}/"
          done

      - name: Commit and push
        run: |
          cd screens-branch
          git add .
          git commit -m "Update reference screenshots"
          git push origin screens --force
