name: Update Screenshots on Code Change

on:
  push:
    branches: [main, master]

env:
  UPDATE_SCREENSHOTS: "true"

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests in screenshot update mode
        run: pytest --browser chromium

      - name: Prepare screens branch
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Создаем чистую папку для скриншотов
          mkdir -p all-screenshots
          find . -path "*/screenshots/reference/*.png" -exec cp --parents {} all-screenshots \;

          # Проверяем наличие скриншотов
          if [ -z "$(find all-screenshots -name '*.png')" ]; then
            echo "Ошибка: скриншоты не найдены!"
            exit 1
          fi

          # Создаем/переключаемся на ветку screens
          if git show-ref --quiet refs/heads/screens; then
            git checkout screens
            git rm -rf .
          else
            git checkout --orphan screens
          fi

          # Переносим ТОЛЬКО скриншоты
          find all-screenshots -mindepth 1 -type d -exec mkdir -p {} \;
          find all-screenshots -name '*.png' -exec mv {} . \;

          # Создаем минимальные необходимые файлы
          echo "# Reference Screenshots" > README.md
          echo "__pycache__/" > .gitignore
          echo "all-screenshots/" >> .gitignore

          # Коммит и push
          git add .
          git commit -m "Update reference screenshots"
          git push origin screens --force

          # Диагностика
          echo "Содержимое ветки screens:"
          find . -type f
