name: Update Screenshots on Code Change

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"

env:
  UPDATE_SCREENSHOTS: "true"

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests in screenshot update mode
        run: pytest --browser chromium

      - name: Prepare screens branch
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          find . -path "*/screenshots/reference/*.png" -exec sh -c '
            for filepath do
              dest="clean-screenshots/$(dirname "$filepath")"
              mkdir -p "$dest"
              cp "$filepath" "$dest"
            done
          ' sh {} +

          if ! find clean-screenshots -name '*.png' -print -quit | grep -q .; then
            echo "Error: No screenshots found!"
            exit 1
          fi

          if git show-ref --quiet refs/heads/screens; then
            git checkout screens
            find . -mindepth 1 ! -name '.git' -exec rm -rf {} +
          else
            git checkout --orphan screens
            git rm -rf .
          fi

          # Копируем структуру и файлы из clean-screenshots в корень ветки
          rsync -a clean-screenshots/ .

          # Создаем минимальные файлы
          echo "# Reference Screenshots" > README.md
          cat > .gitignore << EOF
          __pycache__/
          clean-screenshots/
          allure-results/
          conftest.py
          pytest.ini
          requirements.txt
          EOF

          git add .
          if git diff-index --quiet HEAD --; then
            echo "Нет изменений для коммита"
          else
            git commit -m "Update reference screenshots"
            git push origin screens --force
          fi

          echo "Final branch content:"
          find . -type f
