name: Update Screenshots on Code Change

on:
  push:
    branches: [main, master]

env:
  UPDATE_SCREENSHOTS: "true"

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests in screenshot update mode
        run: pytest --browser chromium

      - name: Prepare screens branch
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Создаем временную папку для новых скриншотов
          mkdir -p temp-screenshots
          find . -path "*/screenshots/reference/*.png" -exec cp --parents {} temp-screenshots \;

          # Переключаемся на ветку screens (создаем если нет)
          if git show-ref --quiet refs/heads/screens; then
            git checkout screens
            git rm -rf . || echo "Nothing to remove"
          else
            git checkout --orphan screens
          fi

          # Очищаем ветку полностью
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

          # Копируем новые скриншоты
          cp -r temp-screenshots/* ./

          # Очистка
          rm -rf temp-screenshots __pycache__ allure-results

          # Коммит и push
          git add .
          if git diff-index --quiet HEAD --; then
            echo "Нет изменений для коммита"
          else
            git commit -m "Auto-update reference screenshots"
            git push origin screens --force
          fi
